homepage/urls.py
from django.urls import path

import homepage.views as views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('logout', views.user_logout, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("", include("homepage.urls")),
    path(
        "accounts/profile/",
        RedirectView.as_view(url="/"),
        name="profile_redirect",
    ),
]

homepage/models.py
from django.db import models


class RandomInteger(models.Model):
    value = models.IntegerField(
        verbose_name="значение",
    )
    updated_at = models.DateTimeField(
        verbose_name="последнее обновление",
        auto_now=True,
    )

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import logout
from django.urls import reverse

from homepage.utils import find_random_integer

user_model = get_user_model()


def homepage(request):
    if request.user.is_authenticated:
        print(request.user)
        print(type(request.user))
    else:
        template_name = "users/login.html"
        return render(
            request,
            template_name,
        )
    context = {
        "rand_int": find_random_integer(),
    }
    template_name = "homepage/homepage.html"
    return render(
        request,
        template_name,
        context,
    )


def user_logout(request):
    logout(request)
    return redirect(
        reverse("homepage:homepage"),
    )

templates/homepage/homepage.html
{% extends "includes/base.html" %}

{% block content %}
<h1 align="center">{{ rand_int }}<h1>
{% endblock %}

templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        
        nav {
            background-color: #333;
        }
        
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
        
        nav ul li {
            float: left;
        }
        
        nav ul li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        
        nav ul li a:hover {
            background-color: #555;
        }        
    </style>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <nav>
        <ul>
            <li><a href="{% url 'homepage:homepage' %}">Home</a></li>
            {% if request.user.is_authenticated %}

            <li><a href="{% url 'homepage:homepage' %}">Пользователь: {{ request.user }}</a></li>
            <li><a href="{% url 'homepage:logout' %}">Выход</a></li>

            {% endif %}

        </ul>
    </nav>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/users/login.html
{% extends "includes/base.html" %}

{% block content %}

<a href="{% url 'social:begin' 'github' %}?next=/">
    <button class="btn btn-primary btn-lg btn-block">
        <i class="fa fa-github"></i> Войти через GitHub
    </button>
</a>

{% endblock %}